# Generated by Django 3.1 on 2023-04-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='emotion',
            field=models.IntegerField(default=0),
        ),
    ]
