# Generated by Django 3.1 on 2023-04-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='angry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='disgust',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='fear',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='happy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='neutral',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='sad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='surprise',
            field=models.IntegerField(default=0),
        ),
    ]
